// Run with: node scripts/addCustomerListOrdered.js          (dry-run — shows what would be added)
// Run with: node scripts/addCustomerListOrdered.js --confirm (actually inserts)
//
// Preserves the exact given order: each new record gets a slightly earlier
// createdAt than the one before it, and the list page's API sorts by
// createdAt descending — so the first name in this list ends up first
// in the table, the second name second, and so on.
const path = require('path');
const fs = require('fs');

const envPath = path.resolve(__dirname, '../.env.local');
console.log('Looking for env file at:', envPath);
console.log('File exists:', fs.existsSync(envPath));

let raw = fs.readFileSync(envPath);
if (raw[0] === 0xFF && raw[1] === 0xFE) {
  raw = raw.toString('utf16le');
} else {
  raw = raw.toString('utf8');
}
raw = raw.replace(/^\uFEFF/, '');

const lines = raw.split(/\r?\n/);
for (const line of lines) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) continue;
  const eqIndex = trimmed.indexOf('=');
  if (eqIndex === -1) continue;
  const key = trimmed.slice(0, eqIndex).trim();
  const value = trimmed.slice(eqIndex + 1).trim();
  process.env[key] = value;
}

console.log('MONGODB_URI loaded as:', process.env.MONGODB_URI);

const mongoose = require('mongoose');

const VisitSchema = new mongoose.Schema({
  date: { type: Date, default: Date.now },
  notes: { type: String },
}, { _id: true, timestamps: false });

const CommentSchema = new mongoose.Schema({
  text: { type: String, required: true },
  date: { type: Date, default: Date.now },
}, { _id: true, timestamps: false });

const MaintenanceSchema = new mongoose.Schema({
  customerName: { type: String, required: true },
  address: { type: String },
  kota: { type: String, required: true },
  wilayah: { type: String },
  phone: { type: String },
  unitType: { type: String },
  serialNumber: { type: String },
  bastDate: { type: Date },
  lastVisitDate: { type: Date },
  nextVisitDate: { type: Date },
  visitCount: { type: Number, default: 0 },
  visitHistory: { type: [VisitSchema], default: [] },
  comments: { type: [CommentSchema], default: [] },
  status: { type: String, enum: ['Active', 'Inactive', 'New'], default: 'New' },
  notes: { type: String },
  perihal: { type: String },
  draftCart: { type: Array, default: [] },
}, { timestamps: true });

const Maintenance = mongoose.models.Maintenance || mongoose.model('Maintenance', MaintenanceSchema);

// Exact verbatim customer list, in the exact order given, matched ONLY
// against the customerName field. kota is a required field on this model,
// so it is set to "-" as a placeholder until filled in per customer.
const CUSTOMER_NAMES = [
  "PT. Yolita Plasinto Pratama ( Ida)",
  "Hendra Dwi Kurniawan",
  "CV Jawa Indah (Ibu Yuli), Samarinda, Kal-Tim",
  " Iskandar",
  " Iskandar",
  " Howard Kasima",
  " Frans Andreas",
  " Fahmuddin Edy Hadi, Yogjakarta",
  "PT. Bertie Sukses Makmur (Andi)",
  "CV Pije Peter Cheryl (Andi)",
  "Hasan Dali",
  " Herry Gunawan",
  " Mirza Budiman Diran",
  " Irawan Susanto",
  " Thio Margaret (Budi)",
  " Esther Indrawati",
  " Suryani",
  " Jonatan Christie",
  "PT. Dwipar Loka Ayu (Aswin)",
  " Erastus Sabdono",
  "Dr. Ketut Ananda W. Sp. OG (Klinik Ananda, Sumba)",
  "Drg. Melanie Hendriaty",
  "Ir. Pudjo Prihadi Santoso",
  " Thakurdas Pursani W",
  " Jenny Lie",
  " Farida Anwari",
  " Syamsuardi Alpat (Sudirman)",
  "Ir. H. Awan Hermawan Purwadinata MT, Bandung",
  " Kusnaeny Mardjoeki (Dini), Surabaya",
  " Doddi Yoshida",
  " Junly Kodradjaya, Surabaya",
  "PT. Dwi Tunggal Putra (Michael)",
  "PT. Multilabindo Wahana (Hidayat)",
  " Felix Claudius Djimin (Greysia/ PT Kreasi Bintang Anugerah)",
  "PT. Barnaby Kontruksi Sejahtera (Hilda)",
  " Andy Indrajaya, ST",
  " Jico Maradona",
  "PT. Esa Pratama (Hafzah)",
  "PT. PT Duta Raya Cipta (Gulshan)",
  " Monica Irmawati Koswara",
  " Ary Indrajanto",
  "Yayasan Perkembangan Anak Indonesia",
  " Suyendi",
  " M. Dodiek Tas'an Wartono",
  " Natalina Surjani .S",
  "PT. Mitra Niaga Nusatama (Jelly)",
  "PT. Layton Enter Prise (Alicia)",
  "Yayasan Karya Kasih Mandiri (Sigit)",
  " Silvi Liswanda",
  " Suwanlia",
  " Sukirman Sutrisno",
  " Johan Suhalim",
  " Abednego Wibowo (Hartono)",
  " Peter Douglas Simpson",
  "PT. Alfa Citra Karyatama (Dr. Hanifah)",
  " Grace Sintjie Soegiarto",
  " Jessica Ronaldy Tjahja (Sumitra)",
  " Linda Tjahja (Rivai)",
  " Leonard Wilson Lay",
  "PT. Semesta Andesit Perkasa (Budi) - PT. Vicindo Jaya Makmur",
  " Aisyah Zaelani (Nur)",
  " Edward",
  " Handoko Sutjitro Surabaya",
  "Ir. Indra Prameswara, SE",
  " Sugiono",
  "Ir. Tjahjono Tjandra",
  " Djohan Surya Adinata",
  " Taruna Wirano Lukman (Rully)",
  " Linda Irawati, Surabaya",
  "PT. Hanny Rancangbangun Abadi",
  " Budi Surjono - Surabaya",
  " Darminto (Eko) / Felicia Nata",
  " Linda Irawati, Surabaya",
  "PT. Comfort Aire Aneka Teknik (Edy - Bintaro)",
  " Lucas Tetardy",
  "Ir. Hardy Tanjaya",
  " Anjar Reksa Permana (Ghani)",
  " Machzum Baisa",
  " Riswandi (Heri Riswandi)-Kalimantan Selatan",
  " Titik Lestari, Bali",
  " Sofian Atmadja Widjaja",
  " Finiantri Sari MSC (Rieke)",
  " Yudi Prawira",
  " Le Agus Felix",
  " Lucian Lewis",
  " Johannes Dhartanto Wibowo (Erman)",
  " Susanti Lukman",
  " Rajulur Rakhman",
  "PT. Jaya Konstruksi Manggala Pratama Tbk,",
  "PT. Wahana Sejahtera Langgeng Makmur ( Howard)",
  "PT Sumberdaya Indonesia (Andi Yusuf - Mangga)",
  " Buyung, Surabaya",
  "PT. Borlindo Mandiri Jaya (Hermon)",
  " Stefanus Yulianto (Evan Malang)",
  " Lesly Irvan",
  " Winarizal",
  "PT. Citra Sembilansatu ( Sahata Saolan Sirait)",
  "PT. Anugerah Aneka Industri (Surja)",
  " Bertha PT Andal Prima Adhitama Perkasa",
  " Ronny Cahyono (PT Usaha Logistik), Surabaya",
  " Heri Hariawan",
  "Maikel Effendi - Ivanna",
  "PT. Sri Buana Sumber Lestari ( Victor)-Surabaya",
  " Stefano Lorenzini",
  "PT. Samudra Wiwaca Kusuma ( Indah)",
  " Henny  Medan",
  " Hendra Surjaputra",
  " Charly Sjaiful",
  "PT Metrindo (Silvia) -Cirebon",
  "Gereja bethany Indonesia (Davy Malada), Gresik",
  "Apartemen Senayan Residence",
  " Pramudya Winarta (PT Ritme Indah)",
  " Peter Chandra-Medan",
  " Harry Yusuf",
  " Ricky Raymond Tjhie",
  " Alexander Tandra",
  "PT. BUMI PURNAMA RAYA (Nanang)",
  "Junial",
  "PT. Adimitra prima Lestari (pak Wily)",
  "Martin Haendra Nata",
  "PT. Griya Trada (Elias Hariwondo)-Jl. Bangka",
  " Yanti Susanti",
  " Suparli",
  "PT. Harimas Tunggal Perkasa (Haryanto)",
  "PT. Golden Bird Metro (Kresna)",
  "CV. Crown Hotel-Kalimantan Utara",
  " Nancy",
  "Arianto Haris- Medan",
  "PT. Mamoru (Wong Sin Yung)",
  "Budi Purnomo (Ibu Lolita)",
  "PT. Gemilang Abadi Santoso ( Unit1 )",
  "PT. Gemilang Abadi Santoso ( Unit2 )",
  "Mr. Hengky Kasim",
  "Mr. Listianingdiah Linggo (Inge)",
  "Mr. Sunata Tjiterosampurno",
  "Mr. Anthony Prayogo",
  "Mr. Daniel Halim",
  "Demo Lift",
  "PT. Global Visi Bersama (Ronald)",
  "Demo Lift",
  "Sasunto",
  "Takdir Mattanete, Surabaya",
  "Hendra Hermanto, Surabaya",
  "Andre Farnandes-MAXIO-Samarinda",
  "Edison Jingga (Hans Jingga)",
  "Wahyu Tri Rahmanto",
  "Syaiful Arifin (Abrian)/ Arnold",
  "Tedy Irawan (Yanto)Palembang",
  "Paulo Roberto Tio",
  "Bambang Triambodo - Makassar",
  "Fonny Makassar",
  "PT Sambas Mineral Mining",
  "PT Griya Selaras Pratama -Pondok Pinang-Klinik Rawamangun",
  "PT Fajar Mitra Krida Abadi - Pak Amir",
  "Vonny- Loranty Noegroho, Yogjakarta",
  "PT. Trishul Indo Sakti, Bali",
  "Herman Mintardja",
  "Suyoto- Kebumen",
  "Dartomo M Sidik - Depok",
  "PT Handal Selaras Maternal-Green Lake",
  "Taufik Hidayat, Palembang",
  "CV Rahmie Group, Gresik",
  "PT. Sari Mas Permai, Wieke , Surabaya",
  "Lie Ly Tedjokoesoemo, Surabaya",
  "Yayasan Onkologi Anak Indonesia",
  "Mohammad Aditya Putra-Eddy Sutrisno",
  "John Marciano- Bali",
  "Gunawan, Jambi",
  "Ike Liemawa",
  "Budi Darmawan, Surabaya",
  "Christine /Michelle / Ong Kim Lian",
  "PT Surya Semesta Permai",
  "Then Kon Pin",
  "Hans Jurgen ",
  "Bintang Jupiter",
  " Ahjiannor, Bupati Kal Teng , Barito",
  "Agung Subagiyo",
  "Drs Nurtjahjo Walujo Wibowo",
  "Ida Yulidina-Paso",
  "Liza Anita Sumarsono,Sonnie Pondok Kopi",
  "PT. Bintang Surya Sejati Sukses/ Budi",
  "PT. Semangat Mekar Jaya Mandiri-Felix Semarang",
  "Ida Sofia SH-Gadog",
  "Andri Pekanbaru",
  "Perseroan Komanditer Primatio (CV)",
  "Ronny Abril",
  "Elly Lestari - Mangga Besar",
  "Elly Lestari -Puncak - 1280x1335-Basement",
  "Elly Lestari - Puncak-1430 x 1335- Meja",
  "Martien Budiman ",
  "Sugeng Mulyono",
  "Intan Cristina Chen",
  "PT Andara Buana Mandiri (NOVIAN)",
  "PT. Danatama Makmur Sekuritas",
  "PT Taktik Promo Sukses",
  "PT. Trika Citriine Abiyasa (Bangun Raharja)",
  "FRANSNICO Bandung",
  "PT. Graha Artha Putra (Elizabeth)",
  "Dinas Pekerjaan Umum dan Penataan Ruang Kota Banjarbaru",
  "Dinas Pekerjaan Umum dan Penataan Ruang Kota Banjarbaru",
  "Subagia Handaja",
  "PT Batara Surya Semesta",
  "Sunarno",
  "Julio - Yonanda Putra",
  "RICKARDO MANGATAS",
  "Sudirman (Alex Kemayoran)",
  "Djohan Darmadi",
  "Bong Lie Fung (Ketsidy)",
  "Feffri Chaidir, SE",
  "PT Rukun Sahabat Senior",
  "Edwin Agung Saputra(Lydia PIK)",
  "Djoko Dermanto",
  "Budiyanto (Kelapa Gading)",
  "Bintang Jupiter - Bali",
  "DRA. ARDINA SAFITRI",
  "Inge Ineke Pieloor",
  "PT Duta Sarana Perkasa-Philips",
  "Eddy Laimancius (CV BajaSakti Trans Perkasa)",
  "Paulus SIA",
  "TH H Handayani Kiroyan",
  "Lionhart Group (Cambodia) Company Limited ",
  "Andrew Sunaryo Gunawan",
  "Christian Bisara",
  "Dian Putri",
  "Mulya Darma Wangsa",
  "Yudi Bandung",
  "Sunarto Rochili - Richard PIK",
  "Rizki Amelia",
  "TIMMOTHY DANIEL RUSLIM (Lusi Summarecon)",
  "Yessi ( PT. Bangun Konstruksi Cemerlang)",
  "Edoardus Ardianto",
  "PT. Sumbersolusindo Hitech (Bpk Hardi)",
  "Yuanita Pangestu-Fery BGV",
  "Eddy Sutomo Santoko PT. CHARMINDO MITRA RAHARJA",
  "MOHAN VASWANI-Malang",
  "Judi Setiawan",
  "Benny Limanto - PIK SKYDANCE",
  "PT Dwibina Prima Patra",
  "DODANI HASSOMAL KU (Hashu)",
  "Dr. Ham Sigit Budiman",
  "Christopher Burke - Bali",
  "ALDO SEBASTIAN SUH",
  "PT Octa Utama (Ifan)",
  "Eddie Darma Salim",
  "Eddie Darma Salim",
  "CV Lautan Berkat Kontruksi-Ms Lisiani-Banyuwangi",
  "Sutiono Sumarno (Ayen)",
  "PT. Nabil Putra Jabal (Budhe-Panglima Polim)",
  "Awie Medan-Suwandi",
  "PT Primaperkasa Intiswadaya (Prayogo)",
  "PT. Maju Makmur Utomo Sunter",
  "PT. Maju Makmur Utomo Sunter",
  "PT. Maju Makmur Utomo Sunter",
  "PT Implementasi Teknologi Indonesia (Arief Sofian)",
  "Djohan Junus Tamsir-Rancamaya",
  "Bpk Gianto Trisno",
  "PT Bumi Bangun Perkasa - Budi BGV",
  "PT. Binayasa Putrabatara",
  "Prof Dr. Maya Devita Lokanata Sp D.V.E",
  "Windri Lestari Rusli",
  "Monica Pranata",
  "PT. First Marine Seafoods",
  "Jaman (Ferry)",
  "Jennifer (PT Karya Anugerah)",
  "Norman S Joesoef (Brawijaya)",
  "PT. Prasetya Mulya Abadi (Setyadi)",
  "Katherina Sulastianus (Renata)",
  "PT Kuala Pangan (Arno)",
  "Andi Azhar Cakra",
  "Mr. Jorge Serrano-Timor Leste",
  "Linas - Bandung",
  "Hargono, Drs-Banjarmasin",
  "PT Semesta Selaras",
  "PT Renata Global Supply",
  "Robin Zulkarnain",
  "Rita Sriyanti - Bandung",
  "Sri Ayu Lestari",
  "PT Intitirta Makmur",
  "UU Sutrisno - Bandung ",
  "Retna Bintarni Oen",
  "Yesaya Milano - Situbondo",
  "PT. Trimitra Alkabes Mandiri -BALI Andreas Hartono Gani",
  "PT. Swi Jetty Nusantara-Makassar",
  "Janne Idris",
  "Like Meilani - Surabaya",
  "Bpk Awong Hidjaya",
  "Rudy Kusmulyadi (Nancy Kelapa Gading)",
  "Dev - Pasar Baru",
  "PT Jaya Kusuma Sarana",
  "DRS. Ricky Irawan",
  "Tinus Thepadjaya",
  "PT Hage Primadi Konstruksi (Ms Priyanka)",
  "PT Pulau Intan (Yashinta Menteng)",
  "PT Hurama Anugerah Berjaya - Robin",
  "PT Hurama Anugerah Berjaya - Vonny",
  "R. Susy Nurhayati - Cirebon",
  "Hasun Lokito-Medan",
  "PT PANEN BERKAT PROPERTINDO-Handoko",
  "Urban Art (Junita-Chandra)",
  "PT. Bima Asri Intermitra",
  "Untung Basuki-Maria - Semarang",
  "Dr. Pengky Pranata-Ms Yulia Sentul",
  "Budi Darmawan, Surabaya",
  "Morgan Arisona",
  "Hendra Jaya MBA",
  "Budi Nuvrizal-Vania",
  "Arif Suhartojo",
  "PT. TURANGGA KERTAKENCANA-Inne",
  "Eastland Development",
  "PT CERIA NUGRAHA ADITAMA  - Kolaka",
  "Yay Budi Siswa  Mr. Pater R.B. Leonardus Evert Bambang Winandoko, SJ",
  "Mr. Oendarno Sinatra",
  "H. Mahmud Fauzi Nasir-Masjid Nurul Amal",
  "PT Permata Sarana Husada ( Dr Novi )",
  "Aspal Polimer Emulsindo - Ibu Nissa Bintaro",
  "Heni Setiawati",
  "PT Persada Dua Rajawali (Will Kramat Sentiong)",
  "Suharto Hadju- Adhyaksa Dault",
  " KSO ADHI-CEC   ",
  "JUJUN TJAKRALAKSAN-Bandung",
  "Dr. Eddy Widodo",
  "Vera Josef Utamin",
  "PT Utama Sinergi Persada-Heryanto- Surabaya",
  "Fatehchand Daulatram Stairlift",
  "JERRY TANDYA  ",
  "Mellyanthy-Budiyanto Intercon",
  "Hartono (Ano)",
  "PT. Karya Akbar Mandiri (Anggia)",
  "Andy Santoso",
  "GRACIA PELITA ABADI-Juan Carlos -Gerry Pulo Gebang",
  "Esmaldiansyah",
  "PT. Hatsonsurya Electric (Hariyanto)-Surabaya",
  "Lionhart Group (Cambodia) Company Limited ",
  "Lionhart Group (Cambodia) Company Limited ",
  "Priska",
  "PT Fukuyama Genki Indonesia-Jason",
  "Gracia Maria Widjajanti H",
  "Silfanni Yanto-BSD",
  "PT. Gagah Putera Satria-Dharma ",
  "Aripin Lie-Pontianak",
  "Tutiawati Subagio",
  "Suwanto - PVE Kantor Artha Gading",
  "PT Shape Up Indonesia- Ibu Lany =MOI",
  "Yulianah Yulianah - Julius",
  "Adam Habibie -Surabaya",
  "Zakaria - Sby",
  "Alfan Koshin-Suriani",
  "Janni BSD",
  "PT Malcolm Indonesia - Kebumen Menteng-Nining",
  "Lo Herry",
  "Gunawan Priatna",
  "Dr Julianus Sloan Soan Petronella",
  "Harsono Smart Clinic",
  "Claudius Marcus",
  "Elsye Augustina Lie",
  "PT PESONA DEWI SRI- Candice - Bali -Villa Dewi Sri blok 1A",
  "PT PESONA DEWI SRI- Candice - Bali -Villa Dewi Sri blok 1B",
  "PT PESONA DEWI SRI- Candice - Bali -Villa Dewi Sri blok 2A",
  "PT PESONA DEWI SRI- Candice - Bali-Villa Dewi Sri blok 2B",
  "Goey Sioe Giok (Bpk Astan) Sunter",
  "Veronica Kadrianto (Vees)",
  "Bpk Harijanto Adipratomo",
  "PT. Nindya Karya (IKN)",
  "CV Ozone Friendly (Johansen Ngian)",
  "Indra Usmansjah Bakrie",
  "PT. Fajar Jasagraha Utama (Grace Irawati)",
  "PT. Total Bangun Persada Tbk-Batam",
  "Mus Abdullah - Pandaan Jawa Timur",
  "Sofiani Iskandarsyah (Ilman)",
  "Jacobus Irawan",
  "Kinanti Purnamasari-Lucy Ciputat Klinik",
  "Clara Fransisca Darniaty",
  "PT Wira Properti (Andy)",
  "Burhanudin (Ebdesk Teknologi- Muhammad Iqbal)",
  "Yurma Welly (Moey Jaya Abadi)",
  "Siauw Santhi",
  "Mus Abdullah - Pandaan Jawa Timur",
  "Bright Future Rocks (Sergei)",
  "Kumar",
  "ANDRI SUWARDI (Hendra)",
  "Duma Riris Silalahi",
  "PT. Lego Merah Indonesia (Vian BSD)",
  "Deepak R Chugani",
  "PT. PRIAMANAYA ENERGI (Rasyad)",
  "Firman Rusli",
  "Djie Anna",
  "Jorge Serrano",
  "ANDRI SUWARDI (Hendra)",
  "PT. Kendali Bumi Sejahtera",
  "Hendra Putra Villa Umalas Bali",
  "Perseroan Terbatas - Badan Joenoes Ikamulya ",
  "Bpk Breav Sugiarto Villa Umalas Bali",
  "Nasir",
  "Feby Joko",
  "Djohan Lawer -  Indayanti Pekanbaru",
  "Fery Godjali",
  "Yunarto (Toni Bali) ",
  "PT Royal Bali Hai",
  "PT. BINTAN LAGOON RESORT",
  "Rika Pauzie",
  "Jandi Djuhari - Bandung-Henru",
  "IR Prihadiyanto",
  "Yuni Handaya",
  "PT Supranusa Sindata (Christian - Stephen Yie)",
  "Eva Pratiwi",
  "AZKA BELLIZA Pak Abdull Rangkas Bitung (ibu Hasnuryani) Dian",
  "Ricky Constantyn Sondakh",
  "Demo Unit Domo2Flex",
  "Endro",
  "Etty Totong",
  "Praditanto Rizabar",
  "PT Bintan Lagoon Resort-Easy Plat",
  "Budhi Pratama Kurniawan",
  "Haris Faisal",
  "Rukun Sahabat Senior (Pak Herman)",
  "PT Alien Bangun Nusantara",
  "PT Adis Dimension Footware (Balaraja)",
  "PT. Gagah Putera Satria-Sandy",
  "Edwin EkaPutra Halim",
  "Gunawan/KusWendy Janur Kelapa Gading/Nike",
  "Etin Sumarni",
  "Rumah Inovasi Sosial Ekologi-for Anomali Caffee",
  "Yonato (Lampung)",
  "Alice Tanizar",
  "Gatot Hidayat",
  "Hendry Wijaya",
  "PT BINA MITRA ARTHA-Jakarta Timur",
  "PT BINA MITRA ARTHA- Jambi",
  "Rahmadia Diwala Putri Bekasi",
  "PT. Paris Jaya (Pak Charlie- Ambon)",
  "PT Karya Perdana Baru",
  "HERLINE EUNIKE DAV/Natanael Walker Bunga Piga/GPDI Greenlake",
  "WINSEN KOESWANTO-Surabaya",
  "Faesal Adli Samvara (Feisal)",
  "Stevanus Rahardja ",
  "Lindawati Pola",
  "Ir Soni/ Russel/ Ibu Enni",
  "Bpk Halim Sudrajat",
  "Annes Suryawinata-PIK",
  "Oktavianti Halim (Frans) ",
  "Cherry Cynthia ",
  "Dr Syifa Mustika-Pandaan ",
  "PT Jeda Property Indonesia - Bali",
  "Muskaan Anil Bahirwani ",
  "Azis",
  "Bong Lhan Lan -Ibu Amy Liong - Kelapa Gading",
  "Hasun Lokito-Medan",
  "PT Sandra Jaya Murni",
  "Muhammad Riza Husn",
  "Dadam Kamil",
  "Karolin Margret Natasa",
  "Jefry Wijaya",
  "Matthew ",
  "Lars Peter Nielsen",
  "Ang Hie Hap /Yenni",
  "PT Pelita Insan Cendika",
  "Demo or Stock Lift Chroma",
  "Simplift Ready Stock",
  "Eddy Budiman (Yossie)",
  "Sarah S Darmawan",
  "Krisdianto Lesmana",
  "Jusuf Kiesworo",
  "Dianto",
  "PT Dwi Tunggal Ekatama/Stefan",
  "Felicita Jetty S Sadeli-BSD",
  "PT. RAYINDO TOROPMA ABADI-RISKA",
  "PT CIME GLOBAL TEKNOLOGI-DEPOK",
  "PT. Pulau Hamparan Pudi",
  "Hamadi Widjaja",
  " Dr. H. Eddy Army Zubair, SH. MH.",
  "PT. Delta Cipta Sinergi",
  "Ernia-REDBERRY INDONESIA",
  "Oki - Milla Pili Oktrianto Bagus R Kottama",
  "Swift Lite STOCK",
  "Herman Tantriady",
  "John Sunarmo",
  "PT.Tiga Puteri Pertiwi Anggi Pancoran",
  " Sugeng Suharyono",
  "Johnny Sentul",
  "PT Pusaka Marmer (Pak Hendrik - Surya Paloh Kapal)",
  "PT. LANCARJAYA MANDIRI ABADI-MUSTARNO",
  "BPK WISHNU HANDOYONO",
  "Tandi Suherman-Pekanbaru--CV SAMPANTAO",
  "Dr Frieda Hartono",
  "David Kosmo",
  "PT Rovin Jaya (Roberto)-NTT Flores",
  "Rangga (Sarie ) ",
  "LANY Kusumadewi Santoso",
  "PT TOTALINDO OPTIAMA PRAGIA",
  "PT TOTALINDO OPTIAMA PRAGIA",
  "Daniel Julian Tang (Tonic Tangkau SH)",
  "Au Chak Man Raymond",
  "PT Intikarya Bangun Mandiri (Supiandi)",
  "Widyani Sutedjo",
  "Hendri Gunawan- Palembang",
  "Lia Femiliawati Dr",
  "Rijanto",
  "ADE MANADO - ABNER DALERU-RANGGA",
  "Hendry Khendy",
  "Johanes Susanto D",
  "Johanes Susanto D",
  "Hendry Khendy",
  "Lianawati Setiono",
];

function norm(s) {
  return (s || '').trim().replace(/\s+/g, ' ').toLowerCase();
}

async function run() {
  const confirm = process.argv.includes('--confirm');

  if (!process.env.MONGODB_URI) {
    throw new Error('MONGODB_URI is undefined — check the path/contents of .env.local above.');
  }

  await mongoose.connect(process.env.MONGODB_URI, { bufferCommands: false });
  console.log('Connected to MongoDB');

  // Check which names already exist, so we don't create true duplicates
  // (still allows the intentional repeats already present in the list, e.g. multiple units).
  const existingDocs = await Maintenance.find({}, { customerName: 1 });
  const existingNames = new Set(existingDocs.map(d => norm(d.customerName)));

  const toInsert = [];
  const alreadyExists = [];

  CUSTOMER_NAMES.forEach((name) => {
    const trimmedName = name.trim().replace(/\s+/g, ' ');
    if (existingNames.has(norm(name))) {
      alreadyExists.push(trimmedName);
      return;
    }
    toInsert.push(trimmedName);
  });

  console.log(`\nTotal names in list: ${CUSTOMER_NAMES.length}`);
  console.log(`Already in database (skipped): ${alreadyExists.length}`);
  if (alreadyExists.length > 0) {
    alreadyExists.forEach(n => console.log('  •', n));
  }

  console.log(`\n${confirm ? 'INSERTING' : 'WOULD INSERT (dry-run)'} — ${toInsert.length} (in the exact order given):`);
  toInsert.forEach((n, i) => console.log(`  ${i + 1}.`, n));

  if (confirm && toInsert.length > 0) {
    // Base timestamp: first item in the list gets the latest createdAt,
    // each subsequent item is 1 second earlier, so sorting by
    // createdAt descending (as the list page does) reproduces this exact order.
    const baseTime = Date.now();
    const docs = toInsert.map((name, i) => ({
      customerName: name,
      kota: '-',
      status: 'New',
      createdAt: new Date(baseTime - i * 1000),
      updatedAt: new Date(baseTime - i * 1000),
    }));
    // timestamps: false tells Mongoose not to overwrite our manually-set
    // createdAt/updatedAt values (the schema has timestamps:true by default).
    const result = await Maintenance.insertMany(docs, { ordered: true, timestamps: false });
    console.log(`\nInserted ${result.length} new customer records, in the exact order given.`);
  } else if (!confirm) {
    console.log('\nDry-run only — nothing was inserted. Re-run with --confirm to actually add these.');
  }

  await mongoose.disconnect();
}

run().catch(err => {
  console.error(err.message);
  process.exit(1);
});