name: Seed Products
on: workflow_dispatch

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Run seed
        env:
          MONGODB_URI: mongodb+srv://vineetadevnani_db_user:vdevnani007@cluster0.ksvbtfj.mongodb.net/stocksystem
        run: |
          mkdir seedrun
          cp seedProducts.js seedrun/
          cd seedrun
          npm init -y
          npm install mongoose
          node seedProducts.js
